# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171109_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 21, 43, 6, 603456)),
        ),
    ]
