# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171109_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 22, 46, 27, 627749)),
        ),
    ]
