# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20171114_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 1, 2, 44, 77146)),
        ),
    ]
