# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
