# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='follow_field',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
    ]
