# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0004_auto_20171109_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='follow_field',
        ),
    ]
