# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together=set([('follower', 'following')]),
        ),
    ]
